export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES_ARRAY: 'SET_CATEGORIES_ARRAY',
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'FETCH_CATEGORIES_FAILED',
};